# Generated by Django 5.0 on 2023-12-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
