# Generated by Django 5.0 on 2023-12-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_patient_date_alter_patient_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='not booked', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.CharField(default='not booked', max_length=1000),
        ),
    ]
