# Generated by Django 5.0 on 2024-01-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_patient_date_alter_patient_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='no_of_cancellation',
            field=models.IntegerField(default=0),
        ),
    ]
