# Generated by Django 5.0 on 2024-01-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_patient_no_of_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cancellation_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
